
version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    container_name: yii2_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_yii
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
